local mod = get_mod("Spidey Sense")
mod.sound = {}
mod.sound.hooked_sounds = {
	"wwise/events/minions/play_enemy_mutant_charger",
	"wwise/events/minions/play_netgunner_footsteps",
	"wwise/events/minions/play_netgunner_run_foley_special",
	"wwise/events/minions/play_netgunner_reload",
	"wwise/events/minions/play_enemy_chaos_hound",
	"wwise/events/minions/play_fly_swarm",
	"wwise/events/minions/play_minion_poxwalker_bomber",
	"wwise/events/minions/play_enemy_combat_poxwalker_bomber",	
  "wwise/events/player/play_backstab_indicator_melee",
	"wwise/events/player/play_backstab_indicator_melee_elite",
	"wwise/events/player/play_backstab_indicator_ranged",	
	"wwise/events/weapon/play_combat_weapon_las_sniper",
	"wwise/events/minions/play_traitor_guard_grenadier",
	"wwise/events/weapon/play_explosion_fuse",
	"wwise/events/minions/play_enemy_cultist_flamer_foley_tank",
	"wwise/events/weapon/play_aoe_liquid_fire_loop",
	"wwise/events/weapon/play_minion_flamethrower_green_wind_up",
	"wwise/events/minions/play_cultist_flamer_foley_gas_loop",
	"wwise/events/weapon/play_minion_flamethrower_start",
  "wwise/events/minions/play_enemy_chaos_ogryn_armoured_executor_a",
  "wwise/events/minions/play_shared_foley_traitor_guard_heavy_run",   
  "wwise/events/minions/play_shared_foley_chaos_ogryn_elites_heavy_run",
  "wwise/events/minions/play_minion_footsteps_chaos_ogryn",
  "wwise/events/minions/play_minion_footsteps_boots_heavy",  
  "wwise/events/minions/play_enemy_daemonhost",  
  "wwise/events/minions/play_enemy_cultist_berzerker",
  "wwise/events/minions/play_enemy_traitor_berzerker",
  "wwise/events/minions/play_shared_foley_chaos_cultist_light_run",  
  "wwise/events/minions/play_minion_footsteps_wrapped_feet_specials",
  "wwise/events/minions/play_cultist_grenadier",
  "wwise/events/minions/play_enemy_character_foley_plague_ogryn",
  "wwise/events/minions/play_enemy_plague_ogryn",
  "wwise/events/minions/play_footstep_boots_heavy_plague_ogryn",
  "wwise/events/minions/play_chaos_spawn",  
  "wwise/events/minions/play_beast_of_nurgle",
  "wwise/events/minions/play_shared_elite_executor_cleave_warning",  
  "play_weapon_netgunner_wind_up",    
  "wwise/events/minions/play_netgunner_proximity_warning",  
  "wwise/events/weapon/play_minion_shotgun_pump",
  "wwise/events/minions/play_enemy_chaos_hound_vce_leap",
  "wwise/events/minions/play_chaos_hound_mutator_vce_leap",
  "wwise/events/weapon/play_special_sniper_flash",  
  "wwise/events/weapon/play_weapon_longlas_minion",
  "spawn",
  "wwise/events/weapon/stop_minion_plasmapistol_charge",
  "wwise/events/weapon/play_minion_plasmapistol_charge",
  "wwise/events/weapon/play_minion_plasmapistol",
  "wwise/events/minions/play_shared_foley_traitor_guard_heavy_run_type_2",
  "wwise/events/minions//play_footstep_boots_medium_enemy"
 }

mod.sound.hooked_external_sounds = {
  "es_daemonhost_vo", 
}